{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" .Values.ingressController.clusterRole.name) }}
{{- if .Values.ingressController.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  {{ .Values.ingressController.clusterRole.name }}
  annotations:
    "helm.sh/resource-policy": keep
rules:
  - apiGroups:
      - "configuration.konghq.com"
    resources:
      - kongclusterplugins
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingressclasses
    verbs:
      - get
      - watch
      - list
{{- end -}}
{{- end }}
