{{- if .Values.autoscaling.enabled }}
{{- if not .Values.global.disableRequestsLimits }}
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: {{ template "kong.fullname" . }}-hpa
  labels:
    {{- include "kong.metaLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ template "kong.fullname" . }}
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
{{- end }}
{{- end }}
