apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.plugins.oidc.secretName }}
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "kong.metaLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
data:
  secret: {{ include "sentinel.oidcSessionSecret" . }}
type: Opaque
